import { useFocusEffect, useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useCallback } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useBasket } from './basket-context'; import { Button, money, ScreenState } from './components'; import { stockLabel } from './mobile-utils'; import type { RootStackParamList } from './navigation-types'; import { sharedStyles as s } from './styles'; import { colors, spacing } from './theme';

export function BasketScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const { basket, loading, error, refresh, update, remove, clear } = useBasket();
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  if (loading) return <View style={s.screen}><ScreenState loading /></View>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.eyebrow}>Your basket</Text><Text style={s.h1}>Ready when you are.</Text>{error ? <Text style={s.error}>{error}</Text> : null}
    {basket.items.length === 0 ? <ScreenState empty="Your basket is empty. Browse the catalogue to get started." /> : basket.items.map((item) => <View key={item.id} style={s.card}><Text style={styles.name}>{item.productName}</Text><Text style={styles.stock}>{stockLabel(item.stockState)}</Text><View style={s.between}><Text style={styles.price}>{money(item.unitPriceMinor)}</Text><View style={s.row}><Pressable accessibilityLabel={`Decrease ${item.productName} quantity`} onPress={() => item.quantity === 1 ? void remove(item.id, item.productId) : void update(item.id, item.productId, item.quantity - 1)} style={styles.step}><Text style={styles.stepText}>-</Text></Pressable><Text style={styles.quantity}>{item.quantity}</Text><Pressable accessibilityLabel={`Increase ${item.productName} quantity`} onPress={() => void update(item.id, item.productId, item.quantity + 1)} style={styles.step}><Text style={styles.stepText}>+</Text></Pressable></View></View><Pressable onPress={() => void remove(item.id, item.productId)}><Text style={styles.remove}>Remove</Text></Pressable></View>)}
    {basket.items.length ? <View style={styles.summary}><View style={s.between}><Text style={s.body}>Subtotal</Text><Text style={styles.total}>{money(basket.subtotalMinor)}</Text></View><Text style={styles.note}>Delivery and VAT-inclusive totals are confirmed before payment.</Text><Button label="Continue to secure checkout" onPress={() => navigation.navigate('Checkout')} icon="lock-closed-outline" /><Button secondary label="Clear basket" onPress={() => void clear()} /></View> : null}
  </ScrollView>;
}
const styles = StyleSheet.create({ name: { color: colors.text, fontSize: 17, fontWeight: '800' }, stock: { color: colors.muted, fontSize: 12, textTransform: 'uppercase' }, price: { color: colors.orange, fontSize: 20, fontWeight: '900' }, step: { width: 40, height: 40, borderRadius: 6, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' }, stepText: { color: colors.text, fontSize: 22 }, quantity: { color: colors.text, minWidth: 24, textAlign: 'center', fontWeight: '800' }, remove: { color: colors.orange, fontWeight: '700' }, summary: { gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: spacing.lg }, total: { color: colors.text, fontSize: 24, fontWeight: '900' }, note: { color: colors.muted, lineHeight: 20 } });
