import * as WebBrowser from 'expo-web-browser';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import type { PublicCheckoutResponse, ShippingMethod, ShippingMethodCode } from '@tcg-hobby/types';
import { apiRequest } from './api'; import { useAuth } from './auth-context'; import { useBasket } from './basket-context'; import { Button, money } from './components'; import type { RootStackParamList } from './navigation-types'; import { sharedStyles as s } from './styles'; import { colors, spacing } from './theme';
import { mobileConfig } from './config';
import { isTrustedCheckoutUrl } from './mobile-utils';

const fields = ['fullName', 'email', 'line1', 'line2', 'city', 'region', 'postalCode'] as const;
type AddressState = Record<(typeof fields)[number], string> & { country: string };
export function CheckoutScreen({ navigation }: NativeStackScreenProps<RootStackParamList, 'Checkout'>) {
  const { token, user } = useAuth(); const { basket, guestItems, refresh } = useBasket(); const [address, setAddress] = useState<AddressState>({ fullName: '', email: user?.email ?? '', line1: '', line2: '', city: '', region: '', postalCode: '', country: 'GB' });
  const [methods, setMethods] = useState<ShippingMethod[]>([]); const [method, setMethod] = useState<ShippingMethodCode>('UK_STANDARD'); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { void apiRequest<ShippingMethod[]>('/v1/shipping-methods?country=GB').then((items) => { setMethods(items); if (items[0]) setMethod(items[0].code); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Delivery options unavailable.')); }, []);
  const submit = async () => { setPending(true); setError(null); try { const result = await apiRequest<PublicCheckoutResponse>('/v1/checkout/session', { method: 'POST', token, body: JSON.stringify({ guestItems, shippingAddress: address, shippingMethodCode: method }) }); if (!isTrustedCheckoutUrl(result.checkoutUrl, mobileConfig.storefrontOrigin)) throw new Error('The secure checkout destination could not be verified.'); await WebBrowser.openBrowserAsync(result.checkoutUrl, { presentationStyle: WebBrowser.WebBrowserPresentationStyle.FULL_SCREEN }); await refresh(); navigation.navigate('Main', { screen: 'Basket' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Checkout unavailable.'); } finally { setPending(false); } };
  return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>Secure checkout</Text><Text style={s.h1}>Delivery details</Text><Text style={s.body}>Your basket is validated again before the secure Stripe payment page opens.</Text>
    {fields.map((field) => { const label = field === 'postalCode' ? 'Postcode' : field === 'line1' ? 'Address line 1' : field === 'line2' ? 'Address line 2 (optional)' : field === 'fullName' ? 'Full name' : field.charAt(0).toUpperCase() + field.slice(1); return <View key={field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} autoCapitalize={field === 'email' ? 'none' : 'words'} keyboardType={field === 'email' ? 'email-address' : 'default'} value={address[field]} onChangeText={(value) => setAddress((current) => ({ ...current, [field]: value }))} style={s.input} /></View>; })}
    <Text style={s.h2}>Delivery method</Text>{methods.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: method === item.code }} key={item.code} onPress={() => setMethod(item.code)} style={[styles.method, method === item.code && styles.methodActive]}><View><Text style={styles.methodName}>{item.name}</Text><Text style={styles.methodCopy}>{item.etaLabel}</Text></View><Text style={styles.methodPrice}>{item.amountMinor ? money(item.amountMinor) : 'Free where eligible'}</Text></Pressable>)}
    <View style={s.between}><Text style={s.body}>Products</Text><Text style={styles.total}>{money(basket.subtotalMinor)}</Text></View>{error ? <Text style={s.error}>{error}</Text> : null}<Button label={pending ? 'Preparing checkout...' : 'Continue to Stripe'} disabled={pending} onPress={() => void submit()} icon="lock-closed-outline" />
  </ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ method: { minHeight: 70, borderRadius: 6, borderWidth: 1, borderColor: colors.line, padding: spacing.md, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, methodActive: { borderColor: colors.orange, backgroundColor: '#18110d' }, methodName: { color: colors.text, fontWeight: '800' }, methodCopy: { color: colors.muted, marginTop: 4 }, methodPrice: { color: colors.orange, fontWeight: '800' }, total: { color: colors.text, fontSize: 22, fontWeight: '900' } });
