import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useEffect, useState } from 'react';
import { FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { PublicProductDetail, PublicProductImage } from '@tcg-hobby/types';
import { apiRequest } from './api'; import { useBasket } from './basket-context'; import { Button, money, ProductCard, ScreenState } from './components'; import { stockLabel } from './mobile-utils'; import type { RootStackParamList } from './navigation-types'; import { sharedStyles as s } from './styles'; import { colors, spacing } from './theme';

export function ProductScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList, 'Product'>) {
  const { add } = useBasket(); const [product, setProduct] = useState<PublicProductDetail | null>(null); const [active, setActive] = useState<PublicProductImage | null>(null); const [error, setError] = useState<string | null>(null); const [adding, setAdding] = useState(false);
  const load = async () => { try { const result = await apiRequest<PublicProductDetail>(`/v1/catalogue/${encodeURIComponent(route.params.slug)}`); setProduct(result); setActive(result.image ?? result.images[0] ?? null); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Product unavailable.'); } };
  useEffect(() => { void load(); }, [route.params.slug]);
  if (!product) return <View style={s.screen}><ScreenState loading={!error} error={error} onRetry={() => void load()} /></View>;
  const addItem = async () => { setAdding(true); try { await add(product.id); navigation.navigate('Main', { screen: 'Basket' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to add this product.'); } finally { setAdding(false); } };
  return <ScrollView style={s.screen} contentContainerStyle={s.content}>
    <View><Text style={s.eyebrow}>{product.game}</Text><Text style={s.h1}>{product.name}</Text></View>
    <View style={styles.gallery}>{active ? <Image source={{ uri: active.url }} accessibilityLabel={active.altText} resizeMode="contain" style={styles.mainImage} /> : <View style={styles.fallback}><Text style={styles.fallbackTitle}>Photography coming soon</Text><Text style={s.body}>Product imagery will be added when approved.</Text></View>}</View>
    {product.images.length > 1 ? <FlatList horizontal data={product.images} keyExtractor={(item) => item.id} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`View ${item.altText}`} onPress={() => setActive(item)} style={[styles.thumb, active?.id === item.id && styles.thumbActive]}><Image source={{ uri: item.url }} resizeMode="contain" style={styles.thumbImage} /></Pressable>} ItemSeparatorComponent={() => <View style={{ width: 8 }} />} /> : null}
    <View style={styles.purchase}><Text style={styles.price}>{money(product.price.amountMinor)}</Text><Text style={[styles.stock, product.stockState === 'LOW_STOCK' && styles.low, product.stockState === 'OUT_OF_STOCK' && styles.out]}>{stockLabel(product.stockState)}</Text>
      {product.freeUkStandardShipping ? <Text style={styles.message}>Free UK standard delivery</Text> : null}{product.purchaseLimit ? <Text style={styles.message}>Limit {product.purchaseLimit} per person or household</Text> : null}
      {error ? <Text style={s.error}>{error}</Text> : null}<Button label={adding ? 'Adding...' : product.purchasable ? 'Add to basket' : 'Unavailable'} disabled={adding || !product.purchasable} onPress={() => void addItem()} icon="bag-add-outline" />
    </View>
    <View style={styles.trust}><Text style={styles.trustItem}>Dispatched within one working day</Text><Text style={styles.trustItem}>Secure checkout</Text><Text style={styles.trustItem}>Packed with collectors in mind</Text></View>
    <View style={styles.info}><Text style={s.h2}>Product information</Text><View style={styles.details}><Text style={styles.detail}>Game: {product.game}</Text>{product.setName ? <Text style={styles.detail}>Set: {product.setName}</Text> : null}{product.productType ? <Text style={styles.detail}>Product type: {product.productType}</Text> : null}{product.language ? <Text style={styles.detail}>Language: {product.language}</Text> : null}<Text style={styles.detail}>Condition: {product.condition.replaceAll('_', ' ').toLowerCase()}</Text></View><Text style={styles.infoHeading}>Overview</Text><Text style={s.body}>{product.longDescription || product.shortDescription}</Text><View style={s.divider} /><Text style={styles.infoHeading}>Delivery and returns</Text><Text style={s.body}>Delivery options and the full returns policy are shown during checkout and on tcg-hobby.co.uk.</Text></View>
    {product.relatedProducts.length ? <View style={styles.info}><Text style={s.h2}>You may also like</Text><FlatList horizontal data={product.relatedProducts} keyExtractor={(item) => item.id} renderItem={({ item }) => <View style={styles.related}><ProductCard product={item} onAdd={add} /></View>} ItemSeparatorComponent={() => <View style={{ width: 12 }} />} showsHorizontalScrollIndicator={false} /></View> : null}
  </ScrollView>;
}
const styles = StyleSheet.create({ gallery: { aspectRatio: 1, borderRadius: 8, backgroundColor: colors.white, overflow: 'hidden' }, mainImage: { width: '100%', height: '100%' }, fallback: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.lg, backgroundColor: colors.surface, gap: spacing.sm }, fallbackTitle: { color: colors.text, fontSize: 20, fontWeight: '900' }, thumb: { width: 74, height: 74, padding: 4, borderRadius: 6, backgroundColor: colors.surface, borderWidth: 2, borderColor: 'transparent' }, thumbActive: { borderColor: colors.orange }, thumbImage: { width: '100%', height: '100%' }, purchase: { gap: spacing.sm }, price: { color: colors.orange, fontSize: 32, fontWeight: '900' }, stock: { color: colors.green, fontWeight: '900', textTransform: 'uppercase' }, low: { color: colors.amber }, out: { color: colors.red }, message: { color: colors.text, fontWeight: '700' }, trust: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: spacing.md, gap: 8 }, trustItem: { color: colors.muted }, info: { gap: spacing.md }, details: { gap: 6 }, detail: { color: colors.muted, textTransform: 'capitalize' }, infoHeading: { color: colors.text, fontSize: 18, fontWeight: '800' }, related: { width: 250 } });
