'use client';
import { useActionState } from 'react';
import { useFormStatus } from 'react-dom';
import { AuthCard, Button, ErrorMessage, FormField, Input } from '@tcg-hobby/ui';
import { requestPasswordResetAction, resetPasswordAction, type PasswordRecoveryState } from '../lib/password-recovery-actions';
const initial: PasswordRecoveryState = { fieldErrors: {} };
function Submit({ label, pending }: { label: string; pending: string }) { const status=useFormStatus(); return <Button className="w-full" type="submit" disabled={status.pending}>{status.pending?pending:label}</Button>; }
export function ForgotPasswordForm(){ const [state,action]=useActionState(requestPasswordResetAction,initial); return <AuthCard title="Reset your password" description="Enter the email address attached to your TCG Hobby account."><form action={action} className="space-y-4" noValidate><FormField label="Email" htmlFor="recovery-email" error={state.fieldErrors.email} required><Input id="recovery-email" name="email" type="email" autoComplete="email" required /></FormField><ErrorMessage>{state.formError}</ErrorMessage>{state.success?<p role="status" className="text-sm text-emerald-300">{state.success}</p>:null}<Submit label="Send reset link" pending="Sending..." /></form></AuthCard>; }
export function ResetPasswordForm({token}:{token:string}){ const [state,action]=useActionState(resetPasswordAction,initial); return <AuthCard title="Choose a new password" description="The link is single-use and expires after one hour."><form action={action} className="space-y-4" noValidate><input type="hidden" name="token" value={token}/><FormField label="New password" htmlFor="reset-password" error={state.fieldErrors.password} required hint="Use at least 10 characters with letters and numbers."><Input id="reset-password" name="password" type="password" autoComplete="new-password" required /></FormField><FormField label="Confirm password" htmlFor="reset-confirm" error={state.fieldErrors.confirmPassword} required><Input id="reset-confirm" name="confirmPassword" type="password" autoComplete="new-password" required /></FormField><ErrorMessage>{state.formError??state.fieldErrors.token}</ErrorMessage>{state.success?<p role="status" className="text-sm text-emerald-300">{state.success} <a className="text-accent" href="/login">Sign in</a>.</p>:null}<Submit label="Update password" pending="Updating..." /></form></AuthCard>; }
