'use client';
import { useState, useTransition } from 'react';
import type { GeneratedContentField, GeneratedProductContent, ProductFactInput, ProductFactKey } from '@tcg-hobby/database';
import { applyProductContentAction, discardProductContentAction, generateProductContentAction, restoreProductContentAction, saveProductFactsAction, setProductReviewLifecycleAction } from '../lib/product-content-actions.server';
import { productFactKeysForAdmin } from '../lib/product-content-config';
type Generation = { id: string; status: string; provider: string; model: string; createdAt: string; generatedContent: GeneratedProductContent; requestedFields: GeneratedContentField[] };
const generationFields: Array<{ key: GeneratedContentField; label: string }> = [
  { key: 'shortDescription', label: 'Short description' }, { key: 'fullDescription', label: 'Full description' },
  { key: 'contents', label: 'Contents' }, { key: 'highlights', label: 'Highlights' },
  { key: 'specificationSummary', label: 'Specification summary' }, { key: 'seoTitle', label: 'SEO title' },
  { key: 'metaDescription', label: 'Meta description' }, { key: 'searchTags', label: 'Search tags' },
  { key: 'suggestedSlug', label: 'Suggested slug' }, { key: 'imageAltText', label: 'Primary image alt text' },
];
export function ProductContentAssistant({ productId, initialFacts, generations, lifecycleState }: { productId: string; initialFacts: ProductFactInput[]; generations: Generation[]; lifecycleState: string }) {
  const [facts, setFacts] = useState<Record<string, ProductFactInput>>(() => Object.fromEntries(productFactKeysForAdmin.map((key) => [key, initialFacts.find((fact) => fact.key === key) ?? { key, value: '', verificationState: 'UNVERIFIED', sourceReference: '' }]))); const [selected, setSelected] = useState<GeneratedContentField[]>(generationFields.map((item) => item.key)); const [message, setMessage] = useState(''); const [pending, startTransition] = useTransition();
  const run = (task: () => Promise<{ ok: boolean; message: string }>) => startTransition(async () => { const result = await task(); setMessage(result.message); if (result.ok) window.location.reload(); });
  const latest = generations[0]; const toggle = (field: GeneratedContentField) => setSelected((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]);
  return <section aria-labelledby="content-assistant-title" className="space-y-6 rounded-lg bg-neutral-900 p-5">
    <div><p className="text-sm font-semibold uppercase text-accent">Assisted content</p><h2 id="content-assistant-title" className="mt-1 text-xl font-black text-neutral-50">Verified facts and draft copy</h2><p className="mt-1 text-sm text-neutral-400">Only verified facts are sent to the provider. Generated copy remains unpublished until reviewed and explicitly applied.</p></div>
    {message ? <p role="status" className="rounded bg-neutral-950 p-3 text-sm text-neutral-200">{message}</p> : null}
    <div className="space-y-3"><h3 className="font-bold text-neutral-50">Structured facts</h3><div className="grid gap-3 lg:grid-cols-2">{productFactKeysForAdmin.map((key) => { const fact = facts[key]!; return <fieldset key={key} className="space-y-2 rounded bg-neutral-950/60 p-3"><legend className="px-1 text-sm font-bold text-neutral-200">{key}</legend><label className="block text-xs text-neutral-400">Value<input value={fact.value} onChange={(event) => setFacts({ ...facts, [key]: { ...fact, value: event.target.value } })} className="mt-1 w-full rounded border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm text-neutral-50" /></label><label className="block text-xs text-neutral-400">Verification<select value={fact.verificationState} onChange={(event) => setFacts({ ...facts, [key]: { ...fact, verificationState: event.target.value as 'VERIFIED' | 'UNVERIFIED' } })} className="mt-1 w-full rounded border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm"><option value="UNVERIFIED">Unverified</option><option value="VERIFIED">Verified</option></select></label><label className="block text-xs text-neutral-400">Source reference<input value={fact.sourceReference ?? ''} onChange={(event) => setFacts({ ...facts, [key]: { ...fact, sourceReference: event.target.value } })} className="mt-1 w-full rounded border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm" /></label></fieldset>; })}</div><button disabled={pending} onClick={() => run(() => saveProductFactsAction(productId, Object.values(facts).filter((fact) => fact.value.trim())))} className="rounded bg-neutral-800 px-4 py-2 font-semibold">Save facts</button></div>
    <div className="space-y-3"><h3 className="font-bold text-neutral-50">Fields to generate or apply</h3><div className="flex flex-wrap gap-3">{generationFields.map((field) => <label key={field.key} className="flex items-center gap-2 text-sm text-neutral-200"><input type="checkbox" checked={selected.includes(field.key)} onChange={() => toggle(field.key)} />{field.label}</label>)}</div><button disabled={pending || !selected.length} onClick={() => run(() => generateProductContentAction(productId, selected))} className="rounded bg-accent px-4 py-2 font-bold text-neutral-950">{pending ? 'Working...' : 'Generate review draft'}</button></div>
    {latest ? <div className="space-y-4 rounded bg-neutral-950/60 p-4"><div><h3 className="font-bold text-neutral-50">Latest generation</h3><p className="text-xs text-neutral-500">{latest.provider} / {latest.model} / {new Date(latest.createdAt).toLocaleString('en-GB')} / {latest.status}</p></div>{latest.generatedContent.missingFactWarnings.length ? <div className="rounded bg-amber-500/10 p-3 text-sm text-amber-100"><strong>Missing-fact warnings</strong><ul className="mt-1 list-disc pl-5">{latest.generatedContent.missingFactWarnings.map((warning, index) => <li key={`${warning}-${index}`}>{warning}</li>)}</ul></div> : null}<dl className="grid gap-3 lg:grid-cols-2">{generationFields.map(({ key, label }) => <div key={key}><dt className="text-xs font-bold uppercase text-neutral-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-neutral-200">{Array.isArray(latest.generatedContent[key]) ? (latest.generatedContent[key] as string[]).join('\n') : String(latest.generatedContent[key] ?? '') || 'No value generated'}</dd></div>)}</dl><div className="flex flex-wrap gap-2">{latest.status === 'DRAFT' ? <><button disabled={pending || !selected.length} onClick={() => run(() => applyProductContentAction(productId, latest.id, selected))} className="rounded bg-accent px-4 py-2 font-bold text-neutral-950">Apply selected fields</button><button disabled={pending} onClick={() => run(() => discardProductContentAction(productId, latest.id))} className="rounded bg-neutral-800 px-4 py-2">Discard draft</button></> : null}{latest.status === 'APPLIED' ? <button disabled={pending} onClick={() => run(() => restoreProductContentAction(productId, latest.id))} className="rounded bg-neutral-800 px-4 py-2">Restore previous content</button> : null}</div></div> : null}
    <div className="flex flex-wrap items-center gap-2 border-t border-neutral-800 pt-4"><span className="mr-2 text-sm text-neutral-400">Current lifecycle: {lifecycleState}</span><button disabled={pending} onClick={() => run(() => setProductReviewLifecycleAction(productId, 'DRAFT'))} className="rounded bg-neutral-800 px-3 py-2 text-sm">Save as draft</button><button disabled={pending} onClick={() => run(() => setProductReviewLifecycleAction(productId, 'AWAITING_REVIEW'))} className="rounded bg-neutral-800 px-3 py-2 text-sm">Ready for review</button></div>
  </section>;
}
